const postsTypes = {
  ADD_POST_START: "ADD_POST_START",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_ERROR: "ADD_POST_ERROR",
  FETCH_POSTS_START: "FETCH_POSTS_START",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  UPDATE_POST_START: "UPDATE_POST_START",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  POST_ERROR: "POST_ERROR",
  POST_IS_LOADING: "POST_IS_LOADING",
  DELETE_POST_START: "DELETE_POST_START",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  SHOW_POPUP: "SHOW_POPUP",
};

export default postsTypes;
