const userTypes = {
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  EMAIL_SIGN_IN_SUCCESS: "EMAIL_SIGN_IN_SUCCESS",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  EMAIL_SIGN_UP_START: "EMAIL_SIGN_UP_START",
  EMAIL_SIGN_UP_SUCCESS: "EMAIL_SIGN_UP_SUCCESS",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  IS_LOADING: "IS_LOADING",
  UPDATE_BALANCE_START: "UPDATE_BALANCE",
  UPDATE_BALANCE_SUCCESS: "UPDATE_BALANCE_SUCCESS",

  UPDATE_USER_PROFILE_START: "UPDATE_USER_PROFILE",
  UPDATE_USER_PROFILE_SUCCESS: "UPDATE_USER_PROFILE_SUCCESS",

  USER_ERROR: "USER_ERROR",
  CHANGE_USER_PASSWORD_START: "CHANGE_USER_PASSWORD_START",
  CHANGE_USER_PASSWORD_SUCCESS: "CHANGE_USER_PASSWORD_SUCCESS",
};

export default userTypes;
