const tradesTypes = {
  ADD_TRADE_START: "ADD_TRADE_START",
  ADD_TRADE_SUCCESS: "ADD_TRADE_SUCCESS",

  FETCH_BALANCE_START: "FETCH_BALANCE_START",
  FETCH_BALANCE_SUCCESS: "FETCH_BALANCE_SUCCESS",

  UPDATE_BALANCE_START: "UPDATE_BALANCE_START",
  UPDATE_BALANCE_SUCCESS: "UPDATE_BALANCE_SUCCESS",
};

export default tradesTypes;
