const tradesTypes = {
  ADD_TRADE_START: "ADD_TRADE_START",
  ADD_TRADE_SUCCESS: "ADD_TRADE_SUCCESS",

  FETCH_BALANCE_START: "FETCH_BALANCE_START",
  FETCH_BALANCE_SUCCESS: "FETCH_BALANCE_SUCCESS",

  UPDATE_BALANCE_START: "UPDATE_BALANCE_START",
  UPDATE_BALANCE_SUCCESS: "UPDATE_BALANCE_SUCCESS",

  FETCH_TRADES_START: "FETCH_TRADES_START",
  FETCH_TRADES_SUCCESS: "FETCH_TRADES_SUCCESS",

  FILTER_TRADES: "FILTER_TRADES",

  REMOVE_TRADE_START: "REMOVE_TRADE_START",
  REMOVE_TRADE_SUCCESS: "REMOVE_TRADE_SUCCESS",

  EDIT_TRADE_START: "EDIT_TRADE_START",
  EDIT_TRADE_SUCCESS: "EDIT_TRADE_SUCCESS",
};

export default tradesTypes;
